# docker-compose.yml

version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://user-db:27017/userdb
    depends_on:
      - user-db

  user-db:
    image: mongo
    container_name: user-db
    ports:
      - "27017:27017"
    volumes:
      - user-db-data:/data/db

volumes:
  user-db-data:
